### ISSUE TITLE
用户数比较大的话，验证会不会存在性能问题？

### ISSUE THREAD

**Issue by shiftwinting** [php-casbin/php-casbin#10]
用户数比较大的话，验证会不会存在性能问题？

**Comment by techoner** [comment]
Please use English in issues.

**Comment by techoner** [comment]
Performance depends on the language itself.
Load the policy by user, cache by custom adapter, or load policy from redis.
It can also be run in `swoole` to improve performance.
You can even choose `Casbin` (golang) or `JCasbin` (java)

**Comment by shiftwinting** [comment]
thks.
