### ISSUE TITLE
Database Adapter class not updated with new updateFilteredPolicies

### ISSUE THREAD

**Issue by hcker2000** [php-casbin/php-casbin#101]
Fatal error: Class CasbinAdapter\Database\Adapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Casbin\Persist\UpdatableAdapter::updateFilteredPolicies)

**Comment by hsluoyz** [comment]
@basakest

**Comment by techoner** [comment]
@hcker2000 It has been fixed by https://github.com/php-casbin/database-adapter/pull/17

**Comment by hcker2000** [comment]
Thanks for the update and all the work you do!
