### ISSUE TITLE
The result after packaging is not as expected 

### ISSUE THREAD

**Issue by ZhangChengLin** [php-casbin/php-casbin#112]
https://github.com/ZhangChengLin/untitled2/blob/0df6993d081f6fb0ce59d89679d585dae268468e/test.php#L18

The result of test.php does not meet expectations. The other two tests meet expectations. What's the problem?
Can be tested directly.

**Comment by ZhangChengLin** [comment]
![image](https://user-images.githubusercontent.com/30773389/135163825-8ab73bce-1b37-4baa-9ef8-965935933321.png)

**Comment by ZhangChengLin** [comment]
获取env部分  没有问题  经过另外 test__OK.php 文件测试。

**Comment by techoner** [comment]
![image](https://user-images.githubusercontent.com/35752209/135192354-1c89444a-2182-4c72-ae57-f8cecec9eb42.png)
@ZhangChengLin This code is of no use .
`parent::__construct(...$params);`  No parameters are actually passed in .
