### ISSUE TITLE
Issue in ManagementEnforcer : getAllSubject/Object... has field indexes hard coded 

### ISSUE THREAD

**Issue by zavre-c** [php-casbin/php-casbin#114]
### ManagementEnforcer has field indexes of policy hard coded 
because of which making changes in order of sub, obj, act or adding priority at beginning breaks the code

I think can be solved by using model to get the correct index.

`$this->model->items['p']->tokens`
or 
`$this->model->offsetGet('p')`

https://github.com/php-casbin/php-casbin/blob/d7b799ce60240155d6d967d9c4d9cc9dd9dddab9/src/ManagementEnforcer.php#L23

**Comment by techoner** [comment]
@zavre-c But how do we get the index of `sub` and the column name of `sub` ?

**Comment by zavre-c** [comment]
Found this in Model.php

`$index = array_search(sprintf("%s_priority", $ptype), $assertion->tokens);`

https://github.com/php-casbin/php-casbin/blob/d7b799ce60240155d6d967d9c4d9cc9dd9dddab9/src/Model/Model.php#L236

**Comment by techoner** [comment]
@zavre-c But this is not perfect, I think we should not search based on the column name, because the column name should also be hard-coded.
