### ISSUE TITLE
Path error in the example code

### ISSUE THREAD

**Issue by evarainy** [php-casbin/php-casbin#12]
Hi, in the example, the following code:

```php
require_once './vendor/autoload.php';
use Casbin\Enforcer;
```

actually should be:

```php
use Casbin/Enforcer;
```

Is this backslash: `\` wrong here?

**Comment by techoner** [comment]
The sample code is error free, please refer to http://php.net/manual/en/language.namespaces.rationale.php

**Comment by evarainy** [comment]
> The sample code is error free, please refer to http://php.net/manual/en/language.namespaces.rationale.php

那可能是我环境问题，我改成"/"后才能正常运行。谢谢！

**Comment by hsluoyz** [comment]
@evarainy official PHP uses backslash: ``\``. I don't know what your PHP environment is, but you should probably use a qualified PHP IDE like ``PhpStorm``, which will parse your code correctly.
