### ISSUE TITLE
array_combine(): Both parameters should have an equal number of elements

### ISSUE THREAD

**Issue by 490626721** [php-casbin/php-casbin#127]
**Describe the bug**
An error occurred while trying to create the RBAC model. 

`array_combine(): Both parameters should have an equal number of elements`

Check the error code address and find that the error exists in line CoreEnforcer.php 645

`{
    "file": "E:\\phpstudy_pro\\WWW\\c.com\\vendor\\casbin\\casbin\\src\\CoreEnforcer.php",
    "line": 645,
    "function": "array_combine",
    "args": [
        [
            "p_sub",
            "p_obj",
            "p_act"
        ],
        [
            "测试, /admin/setup/wx",
            "ANY"
        ]
    ]
}`

It processes "test" and "/ admin / setup / Wx" into one field. The correct one should be

`      [
            "测试“,
            ”/admin/setup/wx",
            "ANY"
        ]`

** php version **
7.3

** SQL version  ** 
5.7.26

** casbin version **
casbinPHP V3.19.0 

** plug-in **
casbin/database-adapter V1.6.0

**Comment by hsluoyz** [comment]
@basakest

**Comment by basakest** [comment]
Can you provide more detailed information? I tried to implement similar logic in the middleware, but failed to reproduce the problem.
<img width="1022" alt="Screen Shot 2021-12-03 at 6 08 54 PM" src="https://user-images.githubusercontent.com/47746206/144585459-2a1ebdd0-ef5d-46d2-94d1-4ddc19df34ae.png">

**Comment by techoner** [comment]
@490626721 Please provide your model file and all policies .

**Comment by 490626721** [comment]
sql data
![1638757113(1)](https://user-images.githubusercontent.com/31122122/144776792-3ef9710d-f631-42f3-b240-77ecea8edf65.png)

thinphp6.0 middleware code
![1638757196(1)](https://user-images.githubusercontent.com/31122122/144776881-ae543763-a218-4945-a4e1-dc17086a42ce.png)

**Comment by 490626721** [comment]
@basakest

**Comment by 490626721** [comment]
error traces
![1638757326(1)](https://user-images.githubusercontent.com/31122122/144777073-784c0436-4433-4f72-9495-883c383495a4.png)

**Comment by 490626721** [comment]
api error trace
![1638760960(1)](https://user-images.githubusercontent.com/31122122/144782080-ad7d1f23-40d3-4eb2-98dd-d1bc8ddf0e60.png)

**Comment by techoner** [comment]
@490626721 This does not tell the problem. Have you made any changes to the adapter?
I guess it may be related to model configuration or loading policies, can you provide a tiny sample?

**Comment by 490626721** [comment]
adapter file
`[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.sub == "root"`

![1638839423(1)](https://user-images.githubusercontent.com/31122122/144947622-bb0b846e-8dab-42ef-84a5-a60d9d8be924.png)


casbinConfig:

`public function casbinConfig (): Enforcer
    {
        $config = [
            'type'     => 'mysql', // mysql,pgsql,sqlite,sqlsrv
            'hostname' => Env::get('database.HOSTNAME'),
            'database' => Env::get('database.DATABASE'),
            'username' => Env::get('database.USERNAME'),
            'password' => Env::get('database.PASSWORD'),
            'hostport' => Env::get('database.HOSTPORT'),
        ];
        $adapter = DatabaseAdapter::newAdapter($config);
        $e =  new Enforcer(config_path() . 'casbin.conf', $adapter);
        return $e;
    }`
![1638839452](https://user-images.githubusercontent.com/31122122/144947657-f5454ed3-4e09-4e92-8e5e-f051d27c8984.png)

**Comment by 490626721** [comment]
I found the problem:
![1638867431(1)](https://user-images.githubusercontent.com/31122122/144997916-d5d45ac1-a1e5-4ad4-a850-322305313731.png)
error file path: casbin\src\Persist\AdapterHelper.php   32 line

Using The getcsv () method causes the program to miss some commas

**Comment by 490626721** [comment]
@techoner

**Comment by 490626721** [comment]
> For `str_getcsv()`, please refer to: https://www.php.net/manual/en/function.str-getcsv.php
> 
> ```
> Note:
> 
> The locale settings are taken into account by this function. If LC_CTYPE is e.g. en_US.UTF-8, strings in one-byte encodings may be read wrongly by this function.
> ```
> 
> In view of this, we need to use `loadPolicyArray` in the DatabaseAdapter. Migrate to [php-casbin/database-adapter#19](https://github.com/php-casbin/database-adapter/issues/19)
> 
> @490626721 By the way, I recommend using [dbal-adapter](https://github.com/php-casbin/dbal-adapter) instead of [database-adapter](https://github.com/php-casbin/database-adapter).

OK, I'll change it now :smile:

**Comment by techoner** [comment]
Closed as resolved.
