### ISSUE TITLE
Could change addPermissionsForUser function declaration

### ISSUE THREAD

**Issue by heqichang** [php-casbin/php-casbin#135]
If i have many permissions need to add, I think it works better to declare it like this
```php
function addPermissionsForUser(string $user, array $permissions): bool
```
I can combine my permissions into a two-dimensional arrays. Like this
```php
$e->addPermissionsForUser('admin', [['article', 'read'], ['article', 'write']])
```

**Comment by hsluoyz** [comment]
@leeqvip plz review

**Comment by leeqvip** [comment]
@heqichang Variable number of arguments used here .
To add permissions in batches, you can use this:
```php
$permissions = [
    ["data1", "read"],
    ["data2", "write"],
];
$e->addPermissionsForUser('admin', ...$permissons);
```

**Comment by heqichang** [comment]
@leeqvip Oh, thank you! I did not notice such usage!
