### ISSUE TITLE
composer is fetching v0.1.1 

### ISSUE THREAD

**Issue by tolgaulas** [php-casbin/php-casbin#143]
When I compare what's fetched and put with the /vendor/casbin/menu and this repo, clearly what's fetched is not a match. Here is the `composer info casbin/casbin`:
```
composer info casbin/casbin
name     : casbin/casbin
descrip. : a powerful and efficient open-source access control library for php projects.
keywords : access control, acl, casbin, rbac
versions : * v0.1.1
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
homepage : 
source   : [git] https://github.com/php-casbin/php-casbin.git 3df83ee844d48ae7888e18e5f58c398e73678871
dist     : [zip] https://api.github.com/repos/php-casbin/php-casbin/zipball/3df83ee844d48ae7888e18e5f58c398e73678871 3df83ee844d48ae7888e18e5f58c398e73678871
path     : ...../vendor/casbin/casbin
names    : casbin/casbin

support
issues : https://github.com/php-casbin/php-casbin/issues
source : https://github.com/php-casbin/php-casbin/tree/master

autoload
psr-4
Casbin\ => src/

requires
php >=5.6.0
symfony/expression-language ^2.8
```

mind the version pls.

**Comment by hsluoyz** [comment]
@tolgaulas hi, can you make a PR to update the docs?

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@tolgaulas  `casbin/menu`? Which project is this? Also casbin v0.1.1 is a very old version, please use the latest version.

**Comment by hsluoyz** [comment]
@tolgaulas

**Comment by hsluoyz** [comment]
@tolgaulas hi, can you make a PR to fix it?

**Comment by xuantianyingjie** [comment]
> > 
> 
> yes ?
> 
> > 
> 
> This is not hand picked. I just pointed out that its default is picking v0.1.1.
> 
> I think you need to add the version key to the composer.json each time you release it. That's how composer works along with gits afaik.

I tried and didn't find this problem. You can execute the command ` composer config -l -g  ` to see the mirror address used, I use: https://repo.packagist.org

**Comment by hsluoyz** [comment]
ping @tolgaulas
