### ISSUE TITLE
How to add user while using RBAC policy?

### ISSUE THREAD

**Issue by pockemon** [php-casbin/php-casbin#20]
Hi,
I've gone through the documentation page of casbin.[How to create rbac_model.conf and
rbac_policy.csv]
Now suppose i've one page called  ``` index.php ``` in my website, so what i want to do is only student with certain user-id[email-id] can only access that page[or can do any action(read or write) on that page].
So i can enforce the rbac policy in the index.php file with following code:
```
require_once './vendor/autoload.php';
use Casbin\Enforcer;
$e = new Enforcer("rbac_model.conf", "rbac_policy.csv");

```
My rbac_model.conf file will be like this:
```
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act
[role_definition]
g = _, _
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

```

and rbac_policy file will look like this [suppose i know the email-id  of student 'hardikrana276@gmail.com']
```
p, hardikrana276@gmail.com, index.php, write

```

Is the above things are fine?

Now what i want to do is i don't know what is every users email-id while enforcing one single .csv file. 
So what i want to do is get the user's email-id from database in php file and to send that email-id to .csv file. 
Is there any way to send that extracted email-id from php file to that .csv file through ```Enforcer```  function or some other way.
Please let me know.

**Comment by techoner** [comment]
Do you want to store the Policy in the database?
Database adapter for PHP-Casbin：https://github.com/php-casbin/database-adapter
Supported php framework：
- [Laravel](https://laravel.com/): The PHP framework for web artisans, via plugin: [laravel-casbin](https://github.com/php-casbin/laravel-casbin)
- [Yii PHP Framework](https://www.yiiframework.com/): A fast, secure, and efficient PHP framework, via plugin: [yii-casbin](https://github.com/php-casbin/yii-casbin)
- [CakePHP](https://cakephp.org/): Build fast, grow solid | PHP Framework, via plugin: [cake-casbin](https://github.com/php-casbin/cake-casbin)
- [ThinkPHP](http://www.thinkphp.cn/): The ThinkPHP framework, via plugin: [think-casbin](https://github.com/php-casbin/think-casbin)
