### ISSUE TITLE
ABAC with php-casbin

### ISSUE THREAD

**Issue by killua-eu** [php-casbin/php-casbin#23]
I read through the casbin main project information on abac but don't really understand how to work with abac. Lets say I have this data:

```
INSERT INTO `article` (`id`, `author`, `name`, `state`, `data`) VALUES
(1,	'michael@example.com',	'My first article', 'published', `article text goes here`),
(2,	'adam@example.com',	'The case for ABAC', 'unpublished', `Abac is cool`);
```

and that I want to 

- deny users from reading unpublished articles, 
- but allow users with role 'reviewer' to read them.

How would I note that? Like this?

```
p, role::reviewer, article/*.state == published, read
g, user:peter, role::reviewer
```

How would I pass the article.state to the enforce function?

**Comment by techoner** [comment]
Can be converted to rbac for easy understanding.

**Comment by hsluoyz** [comment]
Hi @killua-eu , the ABAC logic like ``deny users from reading unpublished articles,`` can be implemented in the matcher. Your model can be:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, "role::reviewer") || r.obj.state == "published") && r.act == "read"
```

The matcher means that either the request user has role ``role::reviewer`` or the object's ``state`` attribute is "published", and the action is "read", then allow the access.

There will only be ``g`` rules in the policy, no ``p`` rules are needed.

```csv
g, user:peter, role::reviewer
```

**Comment by hsluoyz** [comment]
Closed as resolved.
