### ISSUE TITLE
Use C++ to build php-casbin

### ISSUE THREAD

**Issue by romitkarmakar** [php-casbin/php-casbin#40]
@techoner can we use our casbin-cpp project to build the casbin PHP extension. I think it will greatly increase our performance. The cpp-casbin builds into dll file for windows and php also use dll file in windows for extension, so I will with very few modification we can achieve this migration. We can use [PHP-CPP](http://www.php-cpp.com/) for this task.

**Comment by techoner** [comment]
Good idea!
But currently casbin-cpp has just begun.

**Comment by techoner** [comment]
@romitkarmakar Now we have a C++ extension（[C/C++ extension for PHP](https://github.com/php-casbin/casbin)）, it is based on [Casbin-CPP](https://github.com/casbin/casbin-cpp), if you are interested, you can try it.

**Comment by hsluoyz** [comment]
@techoner can we add it as a breaking news to README: https://github.com/php-casbin/php-casbin#php-casbin ?
