### ISSUE TITLE
Add batch operations: AddPolicies() and RemovePolicies() to Management API

### ISSUE THREAD

**Issue by techoner** [php-casbin/php-casbin#41]
Refer to: [Add batch operations: AddPolicies() and RemovePolicies() to Management API](https://github.com/casbin/casbin/pull/388)

**Comment by zhengwhizz** [comment]
我也需要这样的批量操作。。。
坐等。

**Comment by hsluoyz** [comment]
@zhengwhizz please modify your words into English.

**Comment by hsluoyz** [comment]
@zhengwhizz it has been added: https://github.com/php-casbin/php-casbin/pull/47
