### ISSUE TITLE
在laravel 7.10版本中

### ISSUE THREAD

**Issue by surest-sky** [php-casbin/php-casbin#43]
`Call to undefined method stdClass::buildRoleLinks()`

```
public function test()
    {
        $enforcer = new Enforcer(base_path('model.conf'), $this->getAdapter());

        $sub = "alice"; // the user that wants to access a resource.
        $obj = "data1"; // the resource that is going to be accessed.
        $act = "read"; // the operation that the user performs on the resource.
        $enforcer->addRoleForUser('alice', 'admin');
    }

    public function getAdapter()
    {
        $config = [
            'type' => 'mysql',
            'hostname' => env('DB_HOST'),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
        ];
        return Adapter::newAdapter($config);
    }
```

还有一个问题，看文档的话，好像没有告知如何将 policy 持久化到 mysql中，如何建表呢

**Comment by techoner** [comment]
@surest-sky Please use english.

**Comment by hsluoyz** [comment]
@surest-sky Any update?

**Comment by BerSiang** [comment]
He want to ask that "how to persist policy in database like mysql". He doesn't see how to do that in docs.

I think you can read the docs about database adapter section.
[https://casbin.org/docs/en/adapters](https://casbin.org/docs/en/adapters)
If you want to use it in laravel way, you can refer to the source code about [php-casbin/laravel-authz](https://github.com/php-casbin/laravel-authz) ([src/Adapters/DatabaseAdapter.php](https://github.com/php-casbin/laravel-authz/blob/master/src/Adapters/DatabaseAdapter.php)), Or just use this library immediately.

**Comment by BerSiang** [comment]
He want to ask that "how to persist policy in database like mysql, and what is the table schema". He doesn't see this part in docs clearly.

I think you need [php-casbin/dbal-adapter](https://github.com/php-casbin/dbal-adapter).
This adapter will initTable() to create table if table not exist, or you can implement your version by implement  Casbin\Persist\Adapter interface and create laravel db migration (about table schema, you can refer to the [initTable()](https://github.com/php-casbin/dbal-adapter/blob/master/src/Adapter.php#L73) function).

By the way, this library has a version  [php-casbin/laravel-authz](https://github.com/php-casbin/laravel-authz) implement in laravel. You can refer to the library how to implement what I say, or just use it immediately.
