### ISSUE TITLE
Can you please catch up to the latest casbin version

### ISSUE THREAD

**Issue by rus-ik** [php-casbin/php-casbin#44]
As soon as there are many inspiring changes starting from casbin v.2.3..

**Comment by hsluoyz** [comment]
@rus-ik we don't have enough developers to sync all Golang Casbin features to PHP right now. Can you specify a feature or two that you need most?

**Comment by rus-ik** [comment]
I need to have the new ABAC's eval() feature in php-casbin

**Comment by hsluoyz** [comment]
@techoner @nodece @GopherJ @xhy-5000 can anyone take this issue?

**Comment by techoner** [comment]
If I have time, I will add this feature .

**Comment by hsluoyz** [comment]
@rus-ik the `eval()` feature has been added: https://github.com/php-casbin/php-casbin/pull/49
