### ISSUE TITLE
New 2.3.0 release ?

### ISSUE THREAD

**Issue by clement-95** [php-casbin/php-casbin#51]
Hi,

In the issue #44  you added the support of the scaling ABAC model with the `eval()` function (which is awesome btw) but it is not included in the latest release 2.2.0 since it got merged after. So I switched from `2.2.0` to `dev-master` in my project to be able to use that model but it'd be safer to have a release including it.

No rush, but what's your strategy to create a new release / when do you plan to create 2.3.0 ? 

Thank you very much,
Clement

**Comment by hsluoyz** [comment]
@techoner @yk17310320725 can we make a new release?

**Comment by techoner** [comment]
New release: https://github.com/php-casbin/php-casbin/releases/tag/v2.3.0
