### ISSUE TITLE
Use semantic-release to release new versions automatically

### ISSUE THREAD

**Issue by hsluoyz** [php-casbin/php-casbin#52]
Sometimes, users need to wait for a few days to see a new release (https://github.com/php-casbin/php-casbin/issues/51). Our members and maintainers also need to take efforts to make a release manually.

**Comment by hsluoyz** [comment]
@yk17310320725 can you do it?

/cc @techoner

**Comment by yk17310320725** [comment]
Yes, I can do it.

**Comment by hsluoyz** [comment]
@techoner it's really great that we have semantic-release now!
