### ISSUE TITLE
"grouping policy elements do not meet role definition" cannot create roles with domains php-casbin

### ISSUE THREAD

**Issue by otaigbe** [php-casbin/php-casbin#53]
My model definition is this 

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

The standard domain tenant rbac model definition but trying to create or even load the casbin fails with this error
"grouping policy elements do not meet role definition" but if the role params are two it loads but does not register my domains

**Comment by hsluoyz** [comment]
@techoner @yk17310320725 please take a look about this issue.

**Comment by hsluoyz** [comment]
Why is closed?
