### ISSUE TITLE
rbac_with_domain_pattern_model can not work with domain *

### ISSUE THREAD

**Issue by pigochu** [php-casbin/php-casbin#54]
Hi
I am trying examples/rbac_with_domain_pattern_model.conf
I load rbac_with_domain_pattern_policy.csv

I use latest version(2.3.0)

My code

```php
<?php require_once './vendor/autoload.php';

use Casbin\Enforcer;

$e = new Enforcer("config/casbin_model.conf", "config/casbin_policy.csv");

$sub = "alice"; // the user that wants to access a resource.
$obj = "data1"; // the resource that is going to be accessed.
$dom = "domain1";
$act = "read"; // the operation that the user performs on the resource.

var_dump($e->enforce($sub, $dom, $obj, $act));
```
it dump false 
When I change $sub = "bob" , $dom t="domain2" , $obj="data2" , it dump true.
Why alice no perssion ?  does this version support wildcard(*)  ?

**Comment by hsluoyz** [comment]
Hi @pigochu , can you try your model and policy in online editor: https://casbin.org/en/editor to see if it works as expected?

**Comment by pigochu** [comment]
@hsluoyz 
I went to editor to play once and the result was the same
I'm not sure my understanding of wildcard(*) is correct
I am still a newbie .

**Comment by hsluoyz** [comment]
@pigochu please paste all your model, policy, request and result.

**Comment by pigochu** [comment]
@hsluoyz 
I use php-casbin original examples file
examples/rbac_with_domain_pattern_model.conf
examples/rbac_with_domain_pattern_policy.csv

![image](https://user-images.githubusercontent.com/1013744/92938611-573f1f80-f47f-11ea-9c42-50caafd165a9.png)

**Comment by hsluoyz** [comment]
So you want to use * as 3rd arg in g as docs said: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac.

@techoner @yk17310320725 has PHP-Casbin supported this feature?

**Comment by pigochu** [comment]
@hsluoyz 

I try to use addDomainMatchingFunc .. its work 

```php
<?php

require_once './vendor/autoload.php';

use Casbin\Enforcer;

$e = new Enforcer("./rbac_with_domain_pattern_model.conf", "vendor/casbin/casbin/examples/rbac_with_domain_pattern_policy.csv");

// BuiltinOperations::keyMatch()
$e->addDomainMatchingFunc("KeyMatch" , Closure::fromCallable( ["\Casbin\Util\BuiltinOperations","keyMatch"] ));

var_dump($e->enforce("alice", "domain1", "data1", "read"));
var_dump($e->enforce("bob", "domain2", "data2", "read"));
```
result
```text
bool(true)
bool(true)
```

**Comment by hsluoyz** [comment]
@pigochu great! Please close this issue if resolved.

**Comment by pigochu** [comment]
@hsluoyz 
Ok
But I suggest that some explanation may be added because it took me a long time to find
addDomainMatchingFunc and \Casbin\Util\BuiltinOperations

**Comment by hsluoyz** [comment]
@yk17310320725 please add this to official docs

/cc @techoner @nodece
