### ISSUE TITLE
dose it support sub domain wildcard (*) ?

### ISSUE THREAD

**Issue by pigochu** [php-casbin/php-casbin#55]
If I have 5 domains.
I want  define to :

- domain/1 : This domain has child domain 2 and 3.
- domain/1/2
- domain/1/3
- domain/4 : This domain has child domain 5
- domain/4/5

I want  domain/1 admin has full access permision , also has full acess permission on domain/1/* , domain/4 admin has full access on domain/4/*.

so policy maybe

```csv
p, admin, domain/:domainId, data, read
p, admin, domain/:domainId, data, write
p, admin, domain/:domainId/:domainId, data, read
p, admin, domain/:domainId/:domainId, data, write

g, alice, admin, domain/1
g, alice, admin, domain/1/*
g, bob, admin, domain/1/2
g, mary, admin, domain/1/3
```
alice has full access permission on domain/1/2 and domain/1/3  , bob only has access on domain/1/2 

Is it possibile ?

**Comment by hsluoyz** [comment]
@pigochu yes, see: https://casbin.org/docs/en/rbac , search: `AddDomainMatchingFunc`

**Comment by pigochu** [comment]
@hsluoyz 
Thank You , It can work in my php script .
But can not work in casbin-editor , Is there any doc about how to use Key2Match on domain ?

![image](https://user-images.githubusercontent.com/1013744/93033589-726d8300-f669-11ea-8cba-0a1ad554fd84.png)

**Comment by hsluoyz** [comment]
@nodece @zhmushan can we support domain pattern in casbin-editor?

**Comment by hsluoyz** [comment]
@pigochu please use subset loading: https://casbin.org/docs/en/policy-subset-loading

**Comment by nodece** [comment]
@hsluoyz we are going to support domain patter in node-casbin as soon.

**Comment by iqDF** [comment]
Hi @hsluoyz does this wildcard future proof for inserting new objects? What I mean with future proof is that, in the example by @pigochu: 
* Alice has the full access to all `domain/1` items: `domain/1/2` and `domain/1/3`
* Suppose we add `domain/1/27` to domain/1. Does Alice then have access to `domain/1/27`?
