### ISSUE TITLE
Is there an example of FilteredAdapter or implement document ?

### ISSUE THREAD

**Issue by pigochu** [php-casbin/php-casbin#56]
I am trying yii-permission , and post an issue.

https://github.com/php-casbin/yii-permission/issues/6

Becasue every request will query all data from casbin_rule, If i have many domain and user  , the result will be very large.

I think FilteredAdapter may fix the problem , but I can not find any example for php version.
Anyone who has implemented it for mysql( or any database ) ? please provide it , thanks.

**Comment by techoner** [comment]
You can use an adapter that implements `FilteredAdapter`,  but the official has not yet provided such an adapter

**Comment by hsluoyz** [comment]
@yk17310320725

**Comment by techoner** [comment]
@pigochu pigochuNow in the latest version, we have provided the `FilteredAdapter` interface, and have built-in `FileFilteredAdapter`.

**Comment by hsluoyz** [comment]
@pigochu See:

https://github.com/php-casbin/php-casbin/blob/master/src/Persist/FilteredAdapter.php
https://github.com/php-casbin/php-casbin/blob/master/src/Persist/Adapters/FileFilteredAdapter.php

**Comment by pigochu** [comment]
I know there is FilterAdapter originally, I just want to find if anyone implements for database.

**Comment by hsluoyz** [comment]
@pigochu which DB adapter do you use? So we can add the feature to that first.

**Comment by pigochu** [comment]
@hsluoyz 
Thank you
I use yii2 activerecord and mysql , I think `php-casbin/database-adapter ` could implement it for all sql databases.

**Comment by hsluoyz** [comment]
@pigochu can you send an issue to: https://github.com/php-casbin/database-adapter to ask for the `FilteredAdapter` feature, so we can better track the progress?

**Comment by pigochu** [comment]
Thanks
I just added the issue..
https://github.com/php-casbin/database-adapter/issues/4

**Comment by hsluoyz** [comment]
Thanks. Closed here.
