### ISSUE TITLE
An $expression variable is initialized with wrong type which results in fatal error

### ISSUE THREAD

**Issue by andbabkin** [php-casbin/php-casbin#57]
https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/src/Enforcer.php#L556
A variable $expression is initialized as `ExpressionLanguage`, and then used as function argument where `Expression` is required. In most cases it is redefined by value returned from `$expressionLanguage->parse(...)` method, but in one case it is used unchanged:
https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/src/Enforcer.php#L636
It results in a fatal error with message:
```
Object of class Symfony\Component\ExpressionLanguage\ExpressionLanguage could not be converted to string
```

**Comment by hsluoyz** [comment]
@yk17310320725

/cc @techoner

**Comment by techoner** [comment]
This bug was caused after this PR[#49 ]

**Comment by hsluoyz** [comment]
@yk17310320725 please fix.

**Comment by yk17310320725** [comment]
Most of the time using PHP-Casbin will not use `eval()`, so `$expression` will be redefined:

https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/src/Enforcer.php#L561

But using `eval()` will redefine it from :

https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/src/Enforcer.php#L589

I don't know why you have such an error, can you reproduce the error? It is best to paste your configuration file, or you can view the test example of `eval()` for inspiration:

https://github.com/php-casbin/php-casbin/blob/8d6d87011f2c024af409d71534197c50c9767491/tests/Unit/Model/ModelTest.php#L54

@andbabkin

**Comment by andbabkin** [comment]
I have got this error when have forgotten to run database seeder which loads policies and groups to the table. When policies are loaded it works fine. 
I wasn't sure that this is only case when broken part of the code is executed, so I gave you to know about that.

The model used:
```
[request_definition]
r = sub, dom, ser, res, act, obj

[policy_definition]
p = sub, dom, ser, res, act, obj_rule, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[role_definition]
g = _, _

[matchers]
m = g(r.sub, p.sub) && r.dom == p.dom  && r.ser == p.ser && keyMatch2(r.res, p.res) && regexMatch(r.act, p.act) && eval(p.obj_rule)
```

**Comment by yk17310320725** [comment]
I fix this bug, When you do not load policies again, is will throw an EvalFunctionException, and tell your "please make sure rule exists in policy when using eval() in matcher". @andbabkin
