### ISSUE TITLE
Storing comments with policies

### ISSUE THREAD

**Issue by killua-eu** [php-casbin/php-casbin#60]
As the authorization gets more complex, it would be nice to add comments/description to i.e. roles. Would it be possible to have  `$m->addPolicy('g', 'g', $rule, 'this role has a comment');` ? Thanks!

**Comment by hsluoyz** [comment]
@killua-eu how to save this comment value in CSV/DB?

**Comment by killua-eu** [comment]
I prefer using a db driver for most projects, but the question applies to both csv and db .. I'm not sure if this is possible with the current table structure? If not, I'd suggest just adding another column.

**Comment by hsluoyz** [comment]
@techoner I think we can support it by adding another comment column in g rules, but not using it in enforcement.

**Comment by hsluoyz** [comment]
@killua-eu after looking at the code, I found actually you can append a comment string to $rule. It can be saved/loaded through adapters I think.

**Comment by hsluoyz** [comment]
Closed as resolved.
