### ISSUE TITLE
Int type results in multiple entries

### ISSUE THREAD

**Issue by killua-eu** [php-casbin/php-casbin#61]
Lets assume this code:

```php
if (!$m->hasPolicy('g', 'g2', $rule)) {
    $m->addPolicy('g', 'g2', $rule);  
    $e->savePolicy();
}
```
If `$rule = [ '0', '1' ];`, everything works as expected, but if `$rule = [ 0, 1 ];`, the `$m->hasPolicy` always evaluates to false. I'm not sure, why php doesn't throw an exception, because https://github.com/php-casbin/php-casbin/blob/ecc5eb20ab6669045b892247b080853483d7a17d/src/Model/Policy.php#L120 requires `string` and should fail on an `int` due to `declare(strict_types=1);`  on https://github.com/php-casbin/php-casbin/blob/ecc5eb20ab6669045b892247b080853483d7a17d/src/Model/Policy.php#L3

Can anyone reproduce this?

**Comment by killua-eu** [comment]
Aah sorry, my bad, the $rule is passed as `array`, thats why php won't fail. Since members of `$rule` should be `string` only, i suggest type checking (or type casting) to be added to the code.

**Comment by hsluoyz** [comment]
@techoner

**Comment by hsluoyz** [comment]
Resolved.

**Comment by hsluoyz** [comment]
@killua-eu I'm afraid currently there's no way to do static type checking in PHP.

**Comment by killua-eu** [comment]
Hi @hsluoyz , I was thinking to add to https://github.com/php-casbin/php-casbin/blob/ecc5eb20ab6669045b892247b080853483d7a17d/src/Model/Policy.php#L120 something like

```
    public function hasPolicy(string $sec, string $ptype, array $rule): bool
    {
        foreach ($r as $rule) {
            if (!is_string($r)) throw new \Exception('String required.');
        }
        if (!isset($this->items[$sec][$ptype])) {
            return false;
        }

        return in_array($rule, $this->items[$sec][$ptype]->policy, true);
    }
```

**Comment by hsluoyz** [comment]
I think this affects performance a lot. @techoner what do you think?

**Comment by killua-eu** [comment]
Yep, performance might be a problem. I didn't do any measurements though. There might be multiple places where a strict type handling might be beneficial. If you think the performance hit is too much, maybe documenting this would be an alternative or type casting might work too. If unhandled/unknown, it just results into weird behavior.

**Comment by hsluoyz** [comment]
@killua-eu can you make a PR to this repo's README to provide some docs?

**Comment by killua-eu** [comment]
Sure, will do.
