### ISSUE TITLE
Getting all domains that user is in

### ISSUE THREAD

**Issue by killua-eu** [php-casbin/php-casbin#63]
With the model 
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && keyMatch2(r.obj, p.obj) && r.act == p.act
```

I'd like to get a function getDomains('user1', '/a/object/*', 'read') that

- finds the roles attached to `user1`
- returns domains, where the role/user has read access to an object

Thanks in advance

**Comment by hsluoyz** [comment]
@abichinger

/cc @techoner

**Comment by abichinger** [comment]
@killua-eu If you know all domains, you could just iterate over them and try to access the object.
```php
$domains = array_filter($all_domains, function($domain) {
    return $e->enforce('user1', $domain, '/a/object/', 'read');
}
```

**Comment by techoner** [comment]
```
$filteredGroupingPolicy = $e->getFilteredGroupingPolicy(0, "alice");
```
You can gets all the role inheritance rules in the policy, field filters can be specified. Then use `array_filter()` to filter.

**Comment by hsluoyz** [comment]
Closed as resolved.
