### ISSUE TITLE
problem with configuration

### ISSUE THREAD

**Issue by axlthe1** [php-casbin/php-casbin#67]
Hi guys, 

I'm struggling with brand new project using Casbin(it's my first time :) ), I've set up the editor online with this configuration for models:

```ini
 [request_definition]
 r = sub, dom, obj, act
 
 [policy_definition]
 p = sub, dom, obj, act
 
 [role_definition]
 g = _, _, _
 
 [policy_effect]
 e = some(where (p.eft == allow))
 
 [matchers]
 m = (g(r.sub, p.sub, r.dom) && r.obj == p.obj &&  r.act == p.act && p.sub != r.sub) || (r.obj == p.obj &&  r.act == p.act && p.sub == r.sub && r.dom == p.dom) 
 
```

and this is my policy file :

> p,role_admin,p1,A,read
> p,role_admin,p1,A,write
> 
> p,role_L,p1,A,read
> 
> p,role_C,p1,A,reads
> p,role_C,p1,A,write
> 
> p,role_T,p1,A,read
> p,role_T,p1,A,write
> 
> 
> p, carlo,p3,A,read
> 
> g,ale,role_admin,*
> g,mario,role_admin,*
> g,rosy,role_C,p1
> g,jessica,role_C,p1
> g,camilla,role_T,p1
> g,vincenzo,role_L,p1

the tests that I've made are these :

```
vincenzo, p1, A, read //true
vincenzo, p1, A, write //false

ale, p8, A, read //true
ale, p14, A, write //true

mario, pALL, A, read //true
mario, pALL, A, write //true

mario, p1, A, read //true
mario, p1, A, write //true


carlo, p2, A, read //false
carlo, p3, A, read //true
```
under custom config :

```php
> (function() {
>   return {
>     /**
>      * Here is custom functions for Casbin.
>      * Currently, there are built-in globMatch, keyMatch, keyMatch2, keyMatch3, keyMatch4, regexMatch, ipMatch.
>      */
>     functions: {},
>     /**
>      * The value comes from config.functions, Casbin will not use this configuration if the value is undefined.
>      * example:
>      * matchingForGFunction: 'globMatch'
>      * matchingDomainForGFunction: 'keyMatch'
>      */
>     matchingForGFunction: 'keyMatch',
>     matchingDomainForGFunction: 'keyMatch',
>     
>   };
> })();
```
what we want is the possibility to set authorization for multiple domains in one row (actually we use the '*' character  to specify multiple domains but the best option for us is to build a hierarchy of domains. Is it possible?)
and for what we have seen on online editor it works well, anyway if we put this configuration in brand new php project with casbin and prepare a test page with this code:

```php
<php?
require_once './vendor/autoload.php';

use Casbin\Enforcer;

$e = new Enforcer(__DIR__ . "\\casbin_model.conf", __DIR__ . "\\policy.csv");

//test.csv contains the same testas the online editor part.
$res = file_get_contents('./test.csv', true);

$rows = explode("\r\n", $res);

foreach ($rows as $row) {
    if ($row == "")
        echo "//ignore";
    else {
        $params = explode(',', $row);
        $res = $e->enforce($params[0], $params[1], $params[2], $params[3]);
        echo $res;
    }
}
```
with this composer.json
```json
{
  "name": "vendor_name/casbin",
  "require": {
    "casbin/casbin": "v2.4.0"
  }
}

```
I got all false as result.

what have I done wrong? 

I think that the problem is that I've not passed the specific configuration for keyMatch function but sincerely i don't know how to configure that.

can someone help us please?

**Comment by hsluoyz** [comment]
@techoner

**Comment by axlthe1** [comment]
Actually I've solved our problem.

we found some magic inside the AdapterHelper at line 30 :
```php
$tokens = explode(', ', $line);
 ```
the space used as separator prevents the policy to be read, after that I've configured the matching function with this code :

```php
$e = new Enforcer(".\\casbin_model.conf", ".\\policy.csv");

$e->addMatchingFunc('keyMatch2', function (string $key1, string $key2) {
    return BuiltinOperations::keyMatch2($key1, $key2);
});
$e->addDomainMatchingFunc('keyMatch2', function (string $key1, string $key2) {
    return BuiltinOperations::keyMatch2($key1, $key2);
});

```

thanks anyway, I hope this helps someone else

my first problem solved on github 🥇 👍
