### ISSUE TITLE
hasPermissionForUser

### ISSUE THREAD

**Issue by zfjhui** [php-casbin/php-casbin#69]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/40257170/110285846-d40e1900-801e-11eb-8ef6-0bd4fd6259cc.png">
Enforcer::hasPermissionForUser('1', 'project', 'add')     返回的是   false 操作不对吗

**Comment by hsluoyz** [comment]
@zfjhui if you want to `get`, use: https://casbin.org/docs/en/rbac-api#getimplicitpermissionsforuser

If you want to `has`, use: https://casbin.org/docs/en/management-api#enforce
