### ISSUE TITLE
need enforceEx function

### ISSUE THREAD

**Issue by nsnake** [php-casbin/php-casbin#70]
php-casbin had enforce, could add enforceEx function ?

https://casbin.org/docs/en/management-api#enforceex

**Comment by hsluoyz** [comment]
@basakest

**Comment by nisnym** [comment]
Can I start this issue or I need to be assigned?

**Comment by hsluoyz** [comment]
@nisnym please go ahead. Anyone can work on the issues without assignment. We only view code quality.

**Comment by hsluoyz** [comment]
@basakest
