### ISSUE TITLE
AddNamedPolicies() not add authorization rules to the current named policy

### ISSUE THREAD

**Issue by igybb** [php-casbin/php-casbin#75]
I have rules in array, E.g.:
`$rules = [ ["editor", "/admin/dashboard/*", "GET"], ["editor", "/admin/users/edit*", "GET"] ];`

Even though the function from ManagementApi `$e->addPolicies($rules)` returns True, does not add any rules.

For completion only:
If I use E.g. `$e->addPolicy("editor", "/admin/dashboard/*", "GET")`, the function returns True and the rule is added properly.

**Comment by techoner** [comment]
Which adapter do you use ?

**Comment by techoner** [comment]
Move to [#3](https://github.com/php-casbin/codeigniter-permission/issues/3).
