### ISSUE TITLE
array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements

### ISSUE THREAD

**Issue by raymondZhong** [php-casbin/php-casbin#83]
![image](https://user-images.githubusercontent.com/1297621/125838189-e6252cfa-122f-4a6d-9a68-b1123b35c0f6.png)

![image](https://user-images.githubusercontent.com/1297621/125838276-2e2f9d68-2d2d-4540-b3e5-b66fdb6586bc.png)

检查验证的时候出错了

array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements

![image](https://user-images.githubusercontent.com/1297621/125838394-624fedd0-c1f2-4f28-81d7-d81139e6af83.png)

![image](https://user-images.githubusercontent.com/1297621/125838702-0e6ae731-c054-4e95-b7a4-94b7413e4afd.png)

官方编辑器测试通过
Editor  Is  Checked ！

![image](https://user-images.githubusercontent.com/1297621/125838529-6e93a68e-afe8-446a-b987-6521610d385e.png)

**Comment by techoner** [comment]
@raymondZhong The number of request definitions is different from the number of policy definitions .
![image](https://user-images.githubusercontent.com/35752209/125882225-d25de908-9d36-4781-9383-0ec25ce9db70.png)

**Comment by hsluoyz** [comment]
@basakest plz fix
