### ISSUE TITLE
Unable to get property "test" of non-object "r_subParam". why  superAdmin Function  Loop 137 ？

### ISSUE THREAD

**Issue by raymondZhong** [php-casbin/php-casbin#85]
![image](https://user-images.githubusercontent.com/1297621/125954353-978b26aa-49df-45f3-8166-bbca83223296.png)

![image](https://user-images.githubusercontent.com/1297621/125954198-a0021fad-59cb-4856-8c9e-a54d9e8fad69.png)

![6F1FB8FFBE76AFBF903357FC4A7F778B](https://user-images.githubusercontent.com/1297621/125956072-97743d40-6b92-400c-8bd2-b2261d9c10e1.jpg)

why  superAdmin Function  Loop 137 ？

Unable to get property "test" of non-object "r_subParam".

![image](https://user-images.githubusercontent.com/1297621/125951249-7fea3071-a737-470d-9879-64fe50bc9523.png)

@techoner

**Comment by hsluoyz** [comment]
@basakest

**Comment by techoner** [comment]
@raymondZhong 
> why superAdmin Function Loop 137 ？

Each policy will be matched until the match is successful.

>Unable to get property "test" of non-object "r_subParam".

The parameter passed in has no `test` attribute, but one of your policies calls this attribute. In go language, even if false is returned, err will be reported :
```go
	m, _ := model.NewModelFromString(`
[request_definition]
r = sub, router, subParam
[policy_definition]
p = sub, router, sub_rule, eft
[policy_effect]
e = some(where (p_eft == allow)) && !some(where (p_eft == deny))
[role_definition]
g = _,_
[matchers]
m = eval(p.sub_rule) && keyMatch(r.router, p.router) && g(r.sub, p.sub)
`)
	e, _ := casbin.NewEnforcer(m)
	e.AddPolicy("2", "/admin/UserInfo/center", "r.subParam.test == '100'", "allow")
	ok, err := e.Enforce("2", "/admin/UserInfo/center", 2)
	fmt.Println(ok, err) 
```
output:
```
false p.sub_rule should satisfy the syntax of matcher: Unable to access unexported field 'test' in token 'r_subParam.test'
```

**Comment by raymondZhong** [comment]
![image](https://user-images.githubusercontent.com/1297621/126043921-6d40ea59-19e0-49ca-8c68-3dddd30b3a7d.png)

Mybe  GO   can  do  it .

PHP-Casbin  can't do it.
