### ISSUE TITLE
why  the  rule   return false ?

### ISSUE THREAD

**Issue by raymondZhong** [php-casbin/php-casbin#86]
why the rule return false ?

![image](https://user-images.githubusercontent.com/1297621/125961242-6e81468c-581b-45bd-8d6a-d05801759219.png)

![image](https://user-images.githubusercontent.com/1297621/125961312-5869ac07-0f8f-402d-9749-839facfbf1d2.png)

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by techoner** [comment]
@raymondZhong In the example below, the result is as expected .
```php
<?php

require './vendor/autoload.php';

use Casbin\Enforcer;
use Casbin\Model\Model;

$enforcer = new Enforcer(Model::newModelFromString(
    <<<EOT
[request_definition]
r = sub, router, subParam
[policy_definition]
p = sub, router, sub_rule, eft
[policy_effect]
e = some(where (p_eft == allow)) && !some(where (p_eft == deny))
[role_definition]
g = _,_
[matchers]
m = eval(p.sub_rule) && keyMatch(r.router, p.router) && g(r.sub, p.sub)
EOT
));
$enforcer->addPolicies([
    ["2", "/admin/UserInfo/center", "r.subParam.test == '100'", "allow"],
]);

var_dump(
    $enforcer->enforce("2", '/admin/UserInfo/center', (object)["test" => 100]),  // true
    $enforcer->enforce("2", '/admin/UserInfo/center', (object)["test" => 200]) // false
);

```

**Comment by raymondZhong** [comment]
@techoner     please   test  DB 。

![image](https://user-images.githubusercontent.com/1297621/126032187-4fdc4847-e06c-4b18-b4ef-24a127d5e484.png)


return    false .

**Comment by techoner** [comment]
@raymondZhong  Which adapter do you use ? 
```php
<?php

require './vendor/autoload.php';

use Casbin\Enforcer;
use Casbin\Model\Model;
use CasbinAdapter\Database\Adapter as DatabaseAdapter;

$config = [
    'type'     => 'mysql', // mysql,pgsql,sqlite,sqlsrv
    'hostname' => '127.0.0.1',
    'database' => 'test',
    'username' => 'root',
    'password' => 'abc-123',
    'hostport' => '3306',
];
$adapter = DatabaseAdapter::newAdapter($config);

$enforcer = new Enforcer(Model::newModelFromString(
    <<<EOT
[request_definition]
r = sub, router, subParam
[policy_definition]
p = sub, router, sub_rule, eft
[policy_effect]
e = some(where (p_eft == allow)) && !some(where (p_eft == deny))
[role_definition]
g = _,_
[matchers]
m = eval(p.sub_rule) && keyMatch(r.router, p.router) && g(r.sub, p.sub)
EOT
), $adapter);
$enforcer->addPolicies([
    ["2", "/admin/UserInfo/center", "r.subParam.test == '100'", "allow"],
]);

var_dump(
    $enforcer->getPolicy(),
    $enforcer->enforce("2", '/admin/UserInfo/center', (object)["test" => 100]),
    $enforcer->enforce("2", '/admin/UserInfo/center', (object)["test" => 200])
);

```

output：
```
array(1) {
  [0]=>
  array(4) {
    [0]=>
    string(1) "2"
    [1]=>
    string(22) "/admin/UserInfo/center"
    [2]=>
    string(24) "r.subParam.test == '100'"
    [3]=>
    string(5) "allow"
  }
}
bool(true)
bool(false)

```

**Comment by raymondZhong** [comment]
show_dump( $enforcer->getPolicy());
  
![image](https://user-images.githubusercontent.com/1297621/126032561-a753393b-ddfa-4781-9557-0714d19eacbe.png)

**Comment by techoner** [comment]
@raymondZhong Can you provide your complete code? Keep it clean and small. Paste here or upload the compressed package.

**Comment by techoner** [comment]
@raymondZhong Check if you have a deny policy?
```
p, 2, /admin/UserInfo/center, r.subParam.test == '100', deny		
```

**Comment by raymondZhong** [comment]
![image](https://user-images.githubusercontent.com/1297621/126035164-836a9953-3460-4188-9a70-ad44640d8963.png)


mybe   the  bug   in    DBAL .

use CasbinAdapter\DBAL\Adapter;
use CasbinAdapter\DBAL\Adapter as DatabaseAdapter;

**Comment by raymondZhong** [comment]
use CasbinAdapter\Database\Adapter as DatabaseAdapter;

![image](https://user-images.githubusercontent.com/1297621/126035661-5c06d08f-3807-4d31-bc95-ebef2b905c98.png)

It's work.   :)

**Comment by raymondZhong** [comment]
![image](https://user-images.githubusercontent.com/1297621/126035938-e7aaa4cb-34f6-49e3-b10c-3db83fed88ec.png)

![image](https://user-images.githubusercontent.com/1297621/126035944-382f547a-9c09-4a0a-ab41-f1951abb9c4d.png)

Why   2,  /admin/Logout/delete   need  check   .test  ?

**Comment by techoner** [comment]
Your policy calls this attribute .

**Comment by raymondZhong** [comment]
![image](https://user-image@techoner .githubusercontent.com/1297621/126043847-ba9d6c38-0e4d-4ad3-ba80-a2625be1b8e2.png)

Casbin  Editor   is Passed

@techoner

**Comment by techoner** [comment]
@raymondZhong See: https://github.com/php-casbin/php-casbin/issues/85 ，Throwing errors is to catch errors more conveniently, you can use `try{} catch(){}`.

**Comment by raymondZhong** [comment]
Wasted two weeks.
It's so  bad.     Mybe  Go  is  OK.       PHP-Casbin  has too many problems。

**Comment by hsluoyz** [comment]
@basakest

**Comment by techoner** [comment]
@raymondZhong Do you have any proposal ? Welcome to PR .
