### ISSUE TITLE
I get a difference from the web editor to my project

### ISSUE THREAD

**Issue by stonecool** [php-casbin/php-casbin#90]
### Model file
```ini
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj, eft

[role_definition]
g = _, _

[policy_effect]
e = !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj)
```
### Policy File
```csv
p, User, *, allow
p, User, /api/billing/user/*, deny

g, System Admin, User

p, System Admin, /api/billing/user/*, allow
```
#### Test Case
```
System Admin,/api/billing/user/list
```
- web editor: true
- my project(v3.4.1): false

In my opinion, it is good list the version of web editor in the page. Thanks for your job.

**Comment by stonecool** [comment]
In the above example, I think the ``p, System Admin, /api/billing/user/*, allow`` can replace the ``p, User, /api/billing/user/*, deny``, the last one have higher priority. Maybe I am wrong.

**Comment by stonecool** [comment]
I read the [Priority Model](https://casbin.org/docs/en/priority-model) use Implicitly model solve my problem.
But I think the difference is strange still.

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by techoner** [comment]
@hsluoyz @stonecool I think this is a bug in the web editor , the results of php-casbin and [go-casbin](https://github.com/casbin/casbin) are the same.
